services:
  qgis-web:
    build:
      context: .
      dockerfile: Dockerfile

    image: qgis-web:local
    container_name: qgis-web
    restart: unless-stopped

    ports:
      - "${QGIS_WEB_PORT:-3001}:3001"

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Sao_Paulo}

      - CUSTOM_USER=${CUSTOM_USER:-admin}
      - PASSWORD=${PASSWORD:-troque-esta-senha}
      - TITLE=${TITLE:-QGIS Web}

      - HARDEN_DESKTOP=true
      - HARDEN_OPENBOX=true
      - DISABLE_SUDO=true
      - DISABLE_TERMINALS=true
      - START_DOCKER=false
      - RESTART_APP=true

      - SELKIES_UI_SIDEBAR_SHOW_FILES=true
      - SELKIES_FILE_TRANSFERS=upload,download
      - FILE_MANAGER_PATH=/projetos/uploads

      - SELKIES_MANUAL_WIDTH=1920
      - SELKIES_MANUAL_HEIGHT=1080
      - MAX_RES=1920x1080

    volumes:
      - ./config:/config
      - ./projetos:/projetos
      - ./dados:/dados:ro

    shm_size: "2gb"
